### ISSUE TITLE
Broken semver

### ISSUE THREAD

**Issue by g-bartoszek** [Canop/lazy-regex#17]
It seems that required Rust version has been changed without bumping the MAJOR version. It may break compilation of crates depending on `lazy-regex` when the required Rust version is not available. In my case `cargo-make` no longer compiles.

**Comment by Canop** [comment]
The current consensus seems to be that the MINOR version should be updated (cf https://github.com/rust-lang/regex#minimum-rust-version-policy).

But... I didn't even update this minor version because I forgot about this. 

Now, the question is how to proceed. For sure I'll bump at least the minor next time I change the minimal rustc version but what about the current problem in `cargo-make` ? Do you have more to do than just update your CI or rust installation ?

**Comment by Canop** [comment]
I'll see if I can yank the version and release a new minor.

**Comment by g-bartoszek** [comment]
> The current consensus seems to be that the MINOR version should be updated (cf https://github.com/rust-lang/regex#minimum-rust-version-policy).

Oh, I didn't know about that. This is kind of a special situation because Rust 1.64 requires glibc >= 2.17 which, in case of my project, means I'll stuck with 1.63 for some time.

**Comment by Canop** [comment]
Can you run `cargo install cargo-make --locked` ?

**Comment by Canop** [comment]
In the meantime, I yanked the 2.3.2: https://crates.io/crates/lazy-regex/versions

**Comment by g-bartoszek** [comment]
> Can you run `cargo install cargo-make --locked` ?

That solved the problem for me. Thank you!
