### ISSUE TITLE
`raw string literal` with a suffix is invalid

### ISSUE THREAD

**Issue by MrAliSalehi** [Canop/lazy-regex#32]
Hi, Im trying to use this crate for the first time, I have this Regex: `server=(?'url'\\S+?)\\&` which is meant to extract a part of a URL.

this regex is valid obviously and works fine but when I tried to use it with `lazy_regex!` or `regex!` I got this error:

`raw string literal` with a suffix is invalid

```rust
static REG: Lazy<Regex> = lazy_regex!(r#"server=(?'url'\\S+?)\\&"#im);
```
and it also says:

```
regex parse error: server=(?'url'\S+?)\& 
                   ^ error: unrecognized flag
```
(its pointing to the 's' in server )
which doesn't make any sense

**Comment by Canop** [comment]
This regex doesn't look valid to me, with its `(?`. This explains the unrecognized flag.

I don't reproduce the "raw string literal with a suffix is invalid" error. What tool produces it ? Are you sure it's cargo ? Some IDE don't fully support rust string literals.

**Comment by MrAliSalehi** [comment]
this is a valid regex:

https://regex101.com/r/YTIw0M/1

but changing it to `"server=(?P<url>\\S+?)&"m` solved the issue, but still the ?'x' syntax is a valid regex statement

**Comment by Canop** [comment]
There's a Rust flavor in the page you link to. Select it and you'll see that it's not valid.

**Comment by MrAliSalehi** [comment]
why a regex would be different between languages🤔 doesnt make sense

**Comment by Canop** [comment]
Welcome to the regex world!

There's no unique syntax or set of capabilities for regular expressions. Many would argue that flavors with backreferences and look-around assertions like PCRE aren't even regular expressions. Most modern languages distanced themselves from PCRx because of its potential for catastrophic explosions, and the rust crate, inspired by RE2, is a much safer flavor.

Details like unicode support also added some fun in this game...
